# ===== Buckets =====
minio_users:
  - name: backend
    password: "{{ minio_backend_password }}"
    buckets:
      - video-hls
      - video-thumb
    public_buckets:
      - video-hls
      - video-thumb

  - name: loki
    password: "{{ minio_loki_password }}"
    buckets:
      - monitoring-loki