$ANSIBLE_VAULT;1.1;AES256
39613561306232633166343434383333313338376235393233663562303931613262323137353365
3834373061363161336161616639343965653737623162640a393931333530653939663666346233
36646465333337616264376230353965336639663661313638666334383435383939633236306564
6134346533323338340a303639316237656636343638343264633861613039396563376430343435
30373537626165646331613031653262316330343638393037323463353834636161333265633938
38613166386231303563646664383436636531373734353639306265623731376338343639663633
32646236653330313538666466616335663036313737326665633962356165323738613664333664
37343631366262646163623363303762353239356331306461653237636366626361306231666438
37666533613730643339396262323135333062653032613538306263616239613764
