- name: Create mc service user
  ansible.builtin.user:
    name: "{{ minio_mc_user }}"
    group: "{{ minio_group }}"
    system: yes
    shell: /sbin/nologin
    create_home: yes
    home: "{{ minio_mc_home }}"

- name: Ensure mc config directory exists
  ansible.builtin.file:
    path: "{{ minio_mc_config_dir }}"
    state: directory
    owner: "{{ minio_mc_user }}"
    group: "{{ minio_group }}"
    mode: "0700"
