$ANSIBLE_VAULT;1.1;AES256
37656332363662653234623762393433633564326466383361323839383365616136393533303232
3464383032306363303634336632333939343363353434320a366331333234646266396637343937
65353333323332383861643337613135323163626162323334656436303265326535646631643736
3164643835643432620a323664626665306633653431303132383965313162636166616635636664
31353330376633323531653765333334316363326162333034373963643838626232663139376634
32383530643261656236646539336335393132616561623233666638343739613764363230353832
33336437306562323165626237343539306237303262303462653965623764306537366365376564
38623835316139666362393865663865366265306665666362313165376162313366633064616638
30383465353237643866393939643663613363363362326365353063383634323237343833303561
31366564386330313732383364353262343736643661323062663466353566643733333262333165
616230363961623963356133346435366531
